name: Run Appium Tests

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    # Install Android SDK and tools
    - name: Set up Android SDK
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lib32stdc++6 lib32z1 # Dependencies for Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/sdk
        mkdir -p $HOME/sdk/cmdline-tools/latest
        mv $HOME/sdk/cmdline-tools/* $HOME/sdk/cmdline-tools/latest
        yes | $HOME/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/sdk/cmdline-tools/latest/bin/sdkmanager --update

    - name: Install Android Emulator and System Image
      run: |
        yes | $HOME/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"
        yes | $HOME/sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

    - name: Start Android Emulator
      run: |
        nohup $HOME/sdk/emulator/emulator -avd test -no-window -no-audio &
        $HOME/sdk/platform-tools/adb wait-for-device
        $HOME/sdk/platform-tools/adb shell input keyevent 82 # Unlock emulator

    - name: Start Appium
      run: |
        appium --log-level error &
        sleep 10

    - name: Build the solution
      run: dotnet build Notepad.sln

    - name: Run the tests
      run: dotnet test NotepadTestsPom/NotepadTestsPom.csproj

    # Set environment variables for Android SDK
    env:
      ANDROID_SDK_ROOT: $HOME/sdk
      PATH: $HOME/sdk/cmdline-tools/latest/bin:$HOME/sdk/platform-tools:$HOME/sdk/emulator:$HOME/sdk/tools:$HOME/sdk/tools/bin:$PATH
