name: Run Appium Tests on Windows

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Node.js and Appium
      run: |
        choco install nodejs-lts
        npm install -g appium

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Set Android SDK environment variables
      run: echo "ANDROID_SDK_ROOT=C:/Users/runner/AppData/Local/Android/Sdk" >> $GITHUB_ENV

    - name: Set up Emulator Binaries
      run: |
        mkdir -p C:/Users/runner/AppData/Local/Android/Sdk/emulator
        cp tools/emulator.exe C:/Users/runner/AppData/Local/Android/Sdk/emulator/
        cp tools/emulator-check.exe C:/Users/runner/AppData/Local/Android/Sdk/emulator/
        ls C:/Users/runner/AppData/Local/Android/Sdk/emulator

    - name: Download and extract AVD
      run: |
        mkdir -p C:/Users/runner/.android/avd
        tar -xvf avd/Pixel_7_1.avd.tar.xz -C C:/Users/runner/.android/avd/

    - name: Create and start AVD
      run: |
        start C:/Users/runner/AppData/Local/Android/Sdk/emulator/emulator.exe -avd Pixel_7_1 -no-window -no-audio
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run Tests
      run: |
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
      env:
        DOTNET_ROOT: C:/Program Files/dotnet
        PATH: C:/Users/runner/AppData/Local/Android/Sdk/platform-tools;C:/Users/runner/AppData/Local/Android/Sdk/emulator;C:/Users/runner/AppData/Local/Android/Sdk/tools;C:/Users/runner/AppData/Local/Android/Sdk/tools/bin;$PATH