name: Run Appium Tests

on:
  push:
    branches:
      - main
  # pull_request:
    # branches:
    #   - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Android SDK Command-line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip -d $HOME/Android/Sdk/cmdline-tools cmdline-tools.zip
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools/ $HOME/Android/Sdk/cmdline-tools/latest

    - name: Set up Android environment
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Download and extract AVD
      run: |
        mkdir -p $HOME/.android/avd
        cp avd/Pixel_7_1.avd.tar.xz $HOME/.android/avd/
        cd $HOME/.android/avd
        tar -xvf Pixel_7_1.avd.tar.xz
        # Create the .ini file for the AVD
        echo "avd_id=Pixel_7_1" > Pixel_7_1.avd/Pixel_7_1.ini
        echo "path=$HOME/.android/avd/Pixel_7_1.avd" >> Pixel_7_1.avd/Pixel_7_1.ini

    - name: Install SDK packages
      run: |
        yes | sdkmanager --install "emulator" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

    - name: List Emulator Directory
      run: |
        echo "Listing contents of the emulator directory..."
        ls -la $HOME/Android/Sdk/emulator

    - name: Start Emulator
      run: |
        echo "Starting the emulator..."
        echo "Current PATH: $PATH"
        
        adb version || echo "adb command not found, checking if emulator path is correct..."
        
        $HOME/Android/Sdk/emulator/emulator -avd Pixel_7_1 -no-window -no-audio &
        
        adb wait-for-device || echo "Failed to wait for the device"
        adb shell input keyevent 82 || echo "Failed to send input keyevent"

    - name: List AVDs
      run: |
        $HOME/Android/Sdk/emulator/emulator -list-avds

    - name: Wait for Emulator to boot
      run: |
        adb wait-for-device
        adb shell "while [[ \$(getprop sys.boot_completed) != 1 ]]; do sleep 1; done"

    - name: Run Tests
      run: |
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
      env:
        DOTNET_ROOT: /usr/share/dotnet
