name: Android App C# Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386'
        packages: 'platforms;android-33 build-tools;33.0.2 platform-tools emulator'
    
    - name: Install Appium and dependencies
      run: |
        npm install -g appium@latest
        appium driver install uiautomator2
    
    - name: Start Appium Server
      run: appium &  # Start Appium server in the background
    
    - name: Extract Android Virtual Device
      run: |
        mkdir %ANDROID_HOME%\avd
        tar -xJf avd/Pixel_7_1.tar.xz -C %ANDROID_HOME%\avd  # Use -J for faster extraction
    
    - name: Start Android Emulator
      run: |
        %ANDROID_HOME%\emulator\emulator.exe -avd Pixel_7_1 -no-window -no-audio -no-boot-anim &
        %ANDROID_HOME%\platform-tools\adb.exe wait-for-device
        %ANDROID_HOME%\platform-tools\adb.exe shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
    
    - name: Install APK
      run: |
        %ANDROID_HOME%\platform-tools\adb.exe install apk/Notepad.apk
    
    - name: Run POM Tests
      run: dotnet test NotepadTestsPom/NotepadTestsPom.csproj
    
    - name: Run Non-POM Tests
      run: dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: NotepadTestsPom/TestResults
