name: Run Appium Tests

on:
  push:
    branches:
      - main
  # pull_request:
    # branches:
    #   - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget xz-utils
        # Install Node.js and Appium
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g appium

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Android SDK command-line tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -P $HOME/Downloads
        unzip -d $HOME/Android/Sdk/cmdline-tools $HOME/Downloads/commandlinetools-linux-10406996_latest.zip
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/emulator:$HOME/Android/Sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android Emulator and System Image
      run: |
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "emulator" "platform-tools" "platforms;android-29" "system-images;android-29;google_apis;x86_64"

    - name: Create AVD with name Pixel_7
      run: |
        $HOME/Android/Sdk/cmdline-tools/latest/bin/avdmanager create avd -n Pixel_7 -k "system-images;android-29;google_apis;x86_64" -d pixel

    - name: Start AVD
      run: |
        nohup $HOME/Android/Sdk/emulator/emulator -avd Pixel_7 -no-window -no-audio &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run Tests
      run: |
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
      env:
        DOTNET_ROOT: /usr/share/dotnet
        PATH: $HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/emulator:$PATH
