name: Run Appium Tests

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or your desired Java version

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        # Install Node.js and Appium
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g appium

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -P $HOME/sdk/cmdline-tools
        unzip $HOME/sdk/cmdline-tools/commandlinetools-linux-7583922_latest.zip -d $HOME/sdk/cmdline-tools
        rm $HOME/sdk/cmdline-tools/commandlinetools-linux-7583922_latest.zip
        mv $HOME/sdk/cmdline-tools/cmdline-tools $HOME/sdk/cmdline-tools/latest

    - name: Set Android SDK environment variables
      run: echo "ANDROID_SDK_ROOT=$HOME/sdk" >> $GITHUB_ENV

    - name: Install Android Emulator and System Image
      run: |
        yes | $HOME/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/sdk --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
        
    - name: Create and start AVD
      run: |
        echo "no" | $HOME/sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
        nohup $HOME/sdk/emulator/emulator -avd test -no-window -no-audio &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run Tests
      run: |
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csprojnd
      env:
        DOTNET_ROOT: /usr/share/dotnet
        PATH: $HOME/sdk/cmdline-tools/latest/bin:$HOME/sdk/platform-tools:$HOME/sdk/emulator:$HOME/sdk/tools:$HOME/sdk/tools/bin:$PATH
