name: Run Appium Tests

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: '0 16 * * *' # This runs the workflow daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Install Appium
      run: npm install -g appium

    - name: Build the solution
      run: dotnet build Notepad.sln

    - name: Run the tests
      run: dotnet test NotepadTestsPom/NotepadTestsPom.csproj
