name: Android App C# Appium Tests

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install and Run Appium Server
      run: |
        npm install -g appium@2.0.0
        appium driver install uiautomator2
        appium --log appium.log &
    
    - name: Setup and Run ARM Emulator
      run: |
        sdkmanager "system-images;android-30;google_apis;arm64-v8a"
        echo "no" | avdmanager create avd --force -n test_arm64 --abi google_apis/arm64-v8a --package "system-images;android-30;google_apis;arm64-v8a"
        $ANDROID_HOME/emulator/emulator -avd test_arm64 -no-window -no-audio -no-boot-anim &
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
    
    - name: Run Tests
      run: |
        adb install apk/Notepad.apk
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults
    
    - name: Upload Appium Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: appium-logs
        path: appium.log
