name: Run Appium Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Android SDK Command-line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip -d $HOME/Android/Sdk/cmdline-tools cmdline-tools.zip
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools/ $HOME/Android/Sdk/cmdline-tools/latest
        export PATH=$HOME/Android/Sdk/cmdline-tools/latest/bin:$PATH

    - name: Set up Android environment
      run: |
        export ANDROID_HOME=$HOME/Android/Sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "export PATH=$PATH" >> $GITHUB_ENV

    - name: Install SDK packages
      run: |
        yes | sdkmanager --install "emulator" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

    - name: Create AVD
      run: |
        echo "Creating the AVD..."
        echo "no" | avdmanager create avd -n Pixel_7_1 -k "system-images;android-30;google_apis;x86_64" --force

    - name: List AVDs
      run: |
        $HOME/Android/Sdk/emulator/emulator -list-avds

    - name: Start Emulator
      run: |
        echo "Starting the emulator..."
        $HOME/Android/Sdk/emulator/emulator -avd Pixel_7_1 -no-window -no-audio &
        
        # Wait for the emulator to boot
        adb wait-for-device || echo "Failed to wait for the device"
        adb shell input keyevent 82 || echo "Failed to send input keyevent"

    - name: Run Tests
      run: |
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
      env:
        DOTNET_ROOT: /usr/share/dotnet