name: Run Appium Tests

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: '0 16 * * *' # This runs the workflow daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Update to the latest version

    - name: Set up JDK
      uses: actions/setup-java@v3 # Ensure using v3, which supports Node 20
      with:
        java-version: '17' # Use the appropriate Java version

    - name: Install Node.js
      uses: actions/setup-node@v3 # Use the latest version for Node.js 20
      with:
        node-version: '20' # Update to Node.js 20

    - name: Install Appium
      run: npm install -g appium

    - name: Run Tests
      run: |
        # Install necessary dependencies for your tests
        npm install # or your build command
        # Run your tests
        npm test # or the command to run your tests
