name: Android App C# Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386'  # Specific version of command-line tools
        packages: 'platforms;android-33 build-tools-33.0.2 platform-tools emulator'
    
    - name: Install Appium and dependencies
      run: |
        npm install -g appium@2.0.0
        appium driver install uiautomator2
        npm install -g appium-uiautomator2-driver@2.29.6
    
    - name: Start Appium Server
      run: start-process appium
    
    - name: Extract Android Virtual Device
      run: |
        mkdir %ANDROID_HOME%\avd
        tar -xf avd/Pixel_7_1.tar.xz -C %ANDROID_HOME%\avd
    
    - name: Start Android Emulator
      run: |
        %ANDROID_HOME%\emulator\emulator.exe -avd Pixel_7_1 -no-window -no-audio -no-boot-anim &
        %ANDROID_HOME%\platform-tools\adb.exe wait-for-device
    
    - name: Install APK
      run: |
        %ANDROID_HOME%\platform-tools\adb.exe install apk/Notepad.apk
    
    - name: Run POM Tests
      run: dotnet test NotepadTestsPom/NotepadTestsPom.csproj
    
    - name: Run Non-POM Tests
      run: dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: TestResults
