name: Run Appium Tests

on:
  push:
    branches:
     - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Android SDK and Emulator
      run: |
        echo "Installing Android SDK and Emulator..."
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
        # Create the SDK directory
        mkdir -p $HOME/Android/Sdk

        # Download the command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/Android/Sdk/
        rm cmdline-tools.zip
        mv $HOME/Android/Sdk/cmdline-tools $HOME/Android/Sdk/cmdline-tools_latest

        # Add to PATH
        echo "export PATH=\$PATH:$HOME/Android/Sdk/cmdline-tools_latest/bin" >> $GITHUB_ENV

        # Install required SDK components
        yes | $HOME/Android/Sdk/cmdline-tools_latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --install "platform-tools" "platforms;android-30" "emulator"

    - name: Create AVD directory
      run: mkdir -p $HOME/.android/avd

    - name: Extract AVD files
      run: |
        echo "Extracting AVD files..."
        tar -xf avd/Pixel_7_1.tar.xz -C $HOME/.android/avd/

    - name: Start Emulator
      run: |
        echo "Starting the emulator..."
        $HOME/Android/Sdk/emulator/emulator -avd Pixel_7_1 -no-window -no-audio &
        
        # Wait for the emulator to boot (adjust the time if necessary)
        echo "Waiting for the emulator to boot..."
        sleep 60  # wait for 60 seconds to ensure the emulator is ready

        adb wait-for-device || echo "Failed to wait for the device"
        adb shell input keyevent 82 || echo "Failed to send input keyevent"
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.4-7/x64
        ANDROID_HOME: $HOME/Android/Sdk
        PATH: $PATH:/home/runner/Android/Sdk/platform-tools:/home/runner/Android/Sdk/emulator

    - name: Run Tests
      run: |
        echo "Running .NET tests..."
        dotnet test NotepadTestsPom/NotepadTestsPom.csproj
        dotnet test NotepadTestsNoPom/NotepadTestsNoPom.csproj
      env:
        DOTNET_ROOT: /usr/share/dotnet
